apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udp-multicaster
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: udp-multicaster
  namespace: default
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: udp-multicaster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: udp-multicaster
subjects:
- kind: ServiceAccount
  name: udp-multicaster
  namespace: default
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: udp-multicaster
  name: udp-multicaster
spec:
  type: ClusterIP
  ports:
  - name: udp
    protocol: UDP
    port: 9782
    targetPort: 9782
  selector:
    app: udp-multicaster
---

apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: udp-multicaster
  name: udp-multicaster
spec: 
  selector:
    matchLabels:
      app: udp-multicaster
  replicas: 1
  template: 
    metadata: 
      labels:
        app: udp-multicaster
    spec: 
      serviceAccountName: udp-multicaster
      containers: 
        - image: "k8s-udp-multicaster:latest"
          imagePullPolicy: Never
          name: udp-multicaster
          ports: 
          - containerPort: 9782
          env: 
          - name: LISTEN_PORT
            value: "9782"
          - name: SERVICE_NAME
            value: "packet-tool-listeners"
          - name: SERVICE_PORT
            value: "udp"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: packet-tool
    type: listen
  name: packet-tool-listeners
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: udp
    protocol: UDP
    port: 9782
    targetPort: 9782
  selector:
    app: packet-tool
    type: listen
---

apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: packet-tool
    type: listen
  name: packet-tool-listen
spec: 
  selector:
    matchLabels:
      app: packet-tool
      type: listen
  replicas: 3
  template: 
    metadata: 
      labels:
        app: packet-tool
        type: listen
    spec: 
      containers: 
        - image: "packet-tool:latest"
          imagePullPolicy: Never
          name: packet-tool
          ports: 
          - containerPort: 9782
          env: 
          - name: PROTOCOL
            value: "udp"
          - name: LISTEN_HOST
            value: ""
          - name: PORT
            value: "9782"
          - name: TYPE
            value: "LISTEN"
---

apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: packet-tool
    type: send
  name: packet-tool-send
spec: 
  selector:
    matchLabels:
      app: packet-tool
      type: send
  replicas: 1
  template: 
    metadata: 
      labels:
        app: packet-tool
        type: send
    spec: 
      containers: 
      - image: "packet-tool:latest"
        imagePullPolicy: Never
        name: packet-tool
        ports: 
        - containerPort: 9782
        env: 
        - name: PROTOCOL
          value: "udp"
        - name: DIAL_HOST
          value: "udp-multicaster"
        - name: PORT
          value: "9782"
        - name: TYPE
          value: "SEND"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
